import type { Locale } from "./config";

const ru = {
  nav: { incubation: "Инкубация", acceleration: "Акселерация", education: "IT-обучение", startups: "Стартапы", gallery: "Галерея", about: "О нас", apply: "Подать заявку", programs: "Все программы", faq: "FAQ", navigation: "Навигация", contacts: "Контакты", privacy: "Обработка персональных данных", openMenu: "Открыть меню", closeMenu: "Закрыть меню", language: "Язык сайта" },
  footer: { description: "Бизнес-инкубатор Международного казахско-турецкого университета имени Ходжи Ахмеда Ясави.", slogan: "MAKE IDEAS HAPPEN" },
  common: { more: "Подробнее", free: "Бесплатно", paid: "Платная", open: "Набор открыт", soon: "Скоро", closed: "Набор закрыт", weeks: "недель", price: "стоимость", runs: "набора в год", equity: "equity", apply: "Подать заявку", ask: "Задать вопрос" },
  home: {
    eyebrow: "Официальная программа AYU · Туркестан", title: "Твоя идея может", outline: "больше.", description: "Превращаем идеи студентов и исследователей в продукты, пилоты и компании при поддержке Офиса коммерциализации университета.", choose: "Выбрать программу",
    cohort: { open: "Предварительная регистрация открыта", soon: "Следующий набор скоро", closed: "Приём заявок завершён", note: "Даты следующего потока будут объявлены после набора" },
    operator: "Оператор программы", operatorName: "Офис коммерциализации Международного казахско-турецкого университета имени Ходжи Ахмеда Ясави", verify: "Проверить на сайте AYU",
    entry: "Три точки входа", chooseTitle: "Выберите программу", chooseOutline: "под свою стадию.", chooseText: "Начните с результата, который у вас уже есть сегодня — мы поможем выбрать следующий шаг.",
    programTexts: ["Есть идея, исследование или проблема, которую хочется решить.", "Уже есть MVP, пользователи и задача ускорить рост проекта.", "Хотите освоить цифровые навыки и собрать первый проект."],
    proofEye: "Результаты, а не обещания", proofTitle: "Цифры с", proofOutline: "контекстом.", proofText: "Показатели программы поддерживаются в актуальном состоянии командой YASAWI STARTUP.", source: "Официальный источник",
    statLabels: ["участников зарегистрировано", "потоков проведено", "недель инкубации", "стартапов в витрине"], statNotes: ["По данным программы", "Обновляется командой программы", "Три этапа с измеримым результатом", "Считаются по опубликованным проектам"],
    selectionEye: "Прозрачный отбор", selectionTitle: "Что происходит", selectionOutline: "после заявки.", selection: [["Заявка", "Вы выбираете программу и коротко рассказываете о себе или проекте."], ["Проверка", "Команда проверяет соответствие базовым критериям."], ["Знакомство", "Короткое интервью помогает определить подходящий трек."], ["Решение", "Вы получаете ответ и понятные инструкции перед стартом."]],
    help: "Нужна помощь до подачи?", helpText: "Напишите команде:", teamEye: "Люди за программой", teamTitle: "Команда, которой", teamOutline: "можно написать.", teamText: "Состав команды, должности и контакты поддерживаются администраторами YASAWI STARTUP.", teamPhoto: "Фото команды",
    partnersEye: "Инновационная экосистема", partnersTitle: "Наши", partnersOutline: "партнёры.", partnersText: "Организации, с которыми мы развиваем предпринимательство и помогаем командам расти.",
    newsEye: "Новости YASAWI и AYU", newsTitle: "Последние", newsOutline: "события.", universityNews: "Новости университета", openPublication: "Открыть публикацию",
    ctaEye: "Следующий поток начинается с тебя", ctaTitle: "Готов сделать", ctaOutline: "первый шаг?", ctaText: "Заполнение займёт около пяти минут. После отправки вы получите понятный следующий шаг."
  },
  apply: { eye: "Заявка в YASAWI STARTUP", title: "Выберите путь.", outline: "Начните движение.", description: "Выберите программу и расскажите немного о себе. Команда поможет определить следующий шаг.", points: ["Бесплатные программы", "Понятный процесс отбора", "Ответ после рассмотрения"], success: "Заявка принята", thanks: "Спасибо! Команда YASAWI STARTUP свяжется с вами после рассмотрения.", home: "На главную", select: "Выберите программу", name: "Как вас зовут?", namePlaceholder: "Имя и фамилия", phone: "Телефон", idea: "Расскажите о себе или проекте", ideaPlaceholder: "Чему хотите научиться или какую проблему решает ваш проект?", consent: "Я согласен(на) на обработку данных для рассмотрения заявки и ознакомлен(а) с", policy: "политикой конфиденциальности", error: "Не удалось отправить заявку. Попробуйте ещё раз.", sending: "Отправляем…", submit: "Отправить заявку" },
  pages: {
    programs: { eye: "Программы YASAWI STARTUP", title: "Выберите свою", outline: "точку старта.", description: "Освойте цифровые навыки, превратите идею в продукт или ускорьте работающий стартап.", details: "Подробнее о программе", subtitles: ["От идеи до первого продукта", "От MVP к росту", "Навыки для цифрового будущего"] },
    startups: { eye: "Портфолио YASAWI", ideas: "идей.", paths: "траекторий роста.", description: "Исследуйте проекты по направлениям и находите команды, с которыми хочется познакомиться.", choose: "Выберите проект", photo: "Если команда добавила фото, оно появится на карточке. Иначе останется фирменная генеративная композиция.", markets: "Открыты к разным рынкам", marketsTitle: "От социальных проектов", marketsOutline: "до DeepTech.", principles: [["Польза", "Проект решает понятную проблему людей или организаций."], ["Технология", "Команда использует цифровые, инженерные или научные инструменты."], ["Проверка", "Идея проходит интервью, прототипирование и тест спроса."]], story: "Следующая история может быть вашей", big: "Большие проекты начинаются", first: "с первой версии.", launch: "Запустить свой проект" },
    aboutNumbers: { eye: "В цифрах", title: "Рост, который", outline: "можно измерить.", text: "За цифрами — участники, продукты, партнёрства и новый предпринимательский опыт." },
    faq: { title: "Отвечаем", outline: "прямо и по делу.", description: "Всё, что важно знать до подачи заявки и начала программы.", noAnswer: "Не нашли ответ?", write: "Напишите нашей команде.", text: "Подскажем, подходит ли вам программа, и поможем подготовиться." }
  }
};

const kk: typeof ru = {
  nav: { incubation: "Инкубация", acceleration: "Акселерация", education: "IT-оқыту", startups: "Стартаптар", gallery: "Галерея", about: "Біз туралы", apply: "Өтінім беру", programs: "Барлық бағдарламалар", faq: "Жиі сұрақтар", navigation: "Навигация", contacts: "Байланыс", privacy: "Дербес деректерді өңдеу", openMenu: "Мәзірді ашу", closeMenu: "Мәзірді жабу", language: "Сайт тілі" },
  footer: { description: "Қожа Ахмет Ясауи атындағы Халықаралық қазақ-түрік университетінің бизнес-инкубаторы.", slogan: "ИДЕЯҢДЫ ІСКЕ АСЫР" },
  common: { more: "Толығырақ", free: "Тегін", paid: "Ақылы", open: "Қабылдау ашық", soon: "Жақында", closed: "Қабылдау жабық", weeks: "апта", price: "құны", runs: "жылдық қабылдау", equity: "equity", apply: "Өтінім беру", ask: "Сұрақ қою" },
  home: {
    eyebrow: "AYU ресми бағдарламасы · Түркістан", title: "Сенің идеяң", outline: "үлкен іске айналады.", description: "Студенттер мен зерттеушілердің идеяларын университеттің Коммерцияландыру офисінің қолдауымен өнімге, пилотқа және компанияға айналдырамыз.", choose: "Бағдарламаны таңдау",
    cohort: { open: "Алдын ала тіркелу ашық", soon: "Келесі қабылдау жақында", closed: "Өтінім қабылдау аяқталды", note: "Келесі лек мерзімі қабылдау аяқталғаннан кейін жарияланады" },
    operator: "Бағдарлама операторы", operatorName: "Қожа Ахмет Ясауи атындағы Халықаралық қазақ-түрік университетінің Коммерцияландыру офисі", verify: "AYU сайтынан тексеру",
    entry: "Үш бастау нүктесі", chooseTitle: "Өз кезеңіңізге сай", chooseOutline: "бағдарламаны таңдаңыз.", chooseText: "Қазір қолыңызда бар нәтижеден бастаңыз — келесі қадамды таңдауға көмектесеміз.",
    programTexts: ["Іске асырғыңыз келетін идеяңыз, зерттеуіңіз немесе мәселеңіз бар.", "MVP мен пайдаланушылар бар, енді жобаның өсуін жеделдету керек.", "Цифрлық дағдыларды меңгеріп, алғашқы жобаңызды жасағыңыз келеді."],
    proofEye: "Уәде емес, нәтиже", proofTitle: "Мағынасы бар", proofOutline: "көрсеткіштер.", proofText: "Бағдарлама көрсеткіштерін YASAWI STARTUP командасы үнемі жаңартып отырады.", source: "Ресми дереккөз",
    statLabels: ["тіркелген қатысушы", "өткізілген лек", "инкубация аптасы", "витринадағы стартап"], statNotes: ["Бағдарлама деректері бойынша", "Команда жаңартып отырады", "Нәтижесі өлшенетін үш кезең", "Жарияланған жобалар бойынша есептеледі"],
    selectionEye: "Ашық іріктеу", selectionTitle: "Өтінімнен кейін", selectionOutline: "не болады.", selection: [["Өтінім", "Бағдарламаны таңдап, өзіңіз немесе жобаңыз туралы қысқаша айтасыз."], ["Тексеру", "Команда негізгі талаптарға сәйкестікті тексереді."], ["Танысу", "Қысқа сұхбат қолайлы бағытты анықтауға көмектеседі."], ["Шешім", "Жауап пен бастау алдындағы нақты нұсқаулықты аласыз."]],
    help: "Өтінімге дейін көмек керек пе?", helpText: "Командаға жазыңыз:", teamEye: "Бағдарлама командасы", teamTitle: "Тікелей жаза алатын", teamOutline: "мамандар.", teamText: "Команда құрамы, лауазымдар мен байланыстарды YASAWI STARTUP әкімшілері жаңартады.", teamPhoto: "Команда мүшесінің фотосы",
    partnersEye: "Инновациялық экожүйе", partnersTitle: "Біздің", partnersOutline: "серіктестер.", partnersText: "Кәсіпкерлікті бірге дамытып, командалардың өсуіне көмектесетін ұйымдар.",
    newsEye: "YASAWI және AYU жаңалықтары", newsTitle: "Соңғы", newsOutline: "оқиғалар.", universityNews: "Университет жаңалықтары", openPublication: "Жарияланымды ашу",
    ctaEye: "Келесі лек сенен басталады", ctaTitle: "Алғашқы қадамға", ctaOutline: "дайынсың ба?", ctaText: "Өтінімге шамамен бес минут кетеді. Жібергеннен кейін келесі қадамды хабарлаймыз."
  },
  apply: { eye: "YASAWI STARTUP өтінімі", title: "Бағытыңды таңда.", outline: "Қозғалысты баста.", description: "Бағдарламаны таңдап, өзіңіз туралы қысқаша айтыңыз. Команда келесі қадамды анықтауға көмектеседі.", points: ["Тегін бағдарламалар", "Түсінікті іріктеу", "Қаралғаннан кейін жауап"], success: "Өтінім қабылданды", thanks: "Рақмет! YASAWI STARTUP командасы өтінімді қарап, сізбен байланысады.", home: "Басты бетке", select: "Бағдарламаны таңдаңыз", name: "Аты-жөніңіз", namePlaceholder: "Аты-жөні", phone: "Телефон", idea: "Өзіңіз немесе жобаңыз туралы айтыңыз", ideaPlaceholder: "Нені үйренгіңіз келеді немесе жобаңыз қандай мәселені шешеді?", consent: "Өтінімді қарау үшін деректерімді өңдеуге келісемін және", policy: "құпиялық саясатымен таныстым", error: "Өтінім жіберілмеді. Қайталап көріңіз.", sending: "Жіберілуде…", submit: "Өтінімді жіберу" },
  pages: {
    programs: { eye: "YASAWI STARTUP бағдарламалары", title: "Өзіңізге лайық", outline: "бастау нүктесін таңдаңыз.", description: "Цифрлық дағдыны меңгеріңіз, идеяны өнімге айналдырыңыз немесе стартаптың өсуін жеделдетіңіз.", details: "Бағдарлама туралы", subtitles: ["Идеядан алғашқы өнімге дейін", "MVP-ден өсуге дейін", "Цифрлық болашақ дағдылары"] },
    startups: { eye: "YASAWI портфолиосы", ideas: "идея.", paths: "өсу жолы.", description: "Бағыттар бойынша жобаларды зерттеп, танысқыңыз келетін командаларды табыңыз.", choose: "Жобаны таңдаңыз", photo: "Команда фото қосса, ол карточкада көрсетіледі. Фото болмаса фирмалық композиция қалады.", markets: "Әртүрлі нарыққа ашықпыз", marketsTitle: "Әлеуметтік жобалардан", marketsOutline: "DeepTech-ке дейін.", principles: [["Пайда", "Жоба адамдардың немесе ұйымдардың нақты мәселесін шешеді."], ["Технология", "Команда цифрлық, инженерлік не ғылыми құралдарды қолданады."], ["Тексеру", "Идея сұхбат, прототип және сұраныс сынағынан өтеді."]], story: "Келесі оқиға сіздікі болуы мүмкін", big: "Үлкен жобалар", first: "алғашқы нұсқадан басталады.", launch: "Жобамды бастау" },
    aboutNumbers: { eye: "Сандармен", title: "Өлшеуге болатын", outline: "өсім.", text: "Бұл сандардың артында қатысушылар, өнімдер, серіктестік және кәсіпкерлік тәжірибе бар." },
    faq: { title: "Нақты әрі", outline: "түсінікті жауаптар.", description: "Өтінім берер және бағдарлама басталар алдында білу керек мәліметтер.", noAnswer: "Жауап табылмады ма?", write: "Командамызға жазыңыз.", text: "Бағдарламаның сізге сәйкестігін айтып, дайындалуға көмектесеміз." }
  }
};

const en: typeof ru = {
  nav: { incubation: "Incubation", acceleration: "Acceleration", education: "IT training", startups: "Startups", gallery: "Gallery", about: "About", apply: "Apply", programs: "All programs", faq: "FAQ", navigation: "Navigation", contacts: "Contacts", privacy: "Personal data processing", openMenu: "Open menu", closeMenu: "Close menu", language: "Site language" },
  footer: { description: "The business incubator of Khoja Akhmet Yassawi International Kazakh-Turkish University.", slogan: "MAKE IDEAS HAPPEN" },
  common: { more: "Learn more", free: "Free", paid: "Paid", open: "Applications open", soon: "Coming soon", closed: "Applications closed", weeks: "weeks", price: "price", runs: "cohorts per year", equity: "equity", apply: "Apply", ask: "Ask a question" },
  home: {
    eyebrow: "Official AYU program · Turkistan", title: "Your idea can", outline: "go further.", description: "We turn ideas from students and researchers into products, pilots and companies with the support of the University Commercialization Office.", choose: "Choose a program",
    cohort: { open: "Pre-registration is open", soon: "Next cohort coming soon", closed: "Applications are closed", note: "Dates for the next cohort will be announced after registration" },
    operator: "Program operator", operatorName: "Commercialization Office of Khoja Akhmet Yassawi International Kazakh-Turkish University", verify: "Verify on the AYU website",
    entry: "Three ways to begin", chooseTitle: "Choose the program", chooseOutline: "for your current stage.", chooseText: "Start with what you have today — we will help you find the right next step.",
    programTexts: ["You have an idea, research or a problem worth solving.", "You already have an MVP and users, and want to accelerate growth.", "You want digital skills and a first project for your portfolio."],
    proofEye: "Results over promises", proofTitle: "Numbers with", proofOutline: "real context.", proofText: "YASAWI STARTUP administrators keep program indicators up to date.", source: "Official source",
    statLabels: ["registered participants", "cohorts completed", "weeks of incubation", "startups in the showcase"], statNotes: ["Based on program data", "Updated by the program team", "Three stages with measurable outcomes", "Calculated from published projects"],
    selectionEye: "Transparent selection", selectionTitle: "What happens", selectionOutline: "after you apply.", selection: [["Application", "Choose a program and briefly introduce yourself or your project."], ["Review", "The team checks your fit against the basic criteria."], ["Conversation", "A short interview helps identify the right track."], ["Decision", "You receive an answer and clear instructions before the program begins."]],
    help: "Need help before applying?", helpText: "Write to the team:", teamEye: "People behind the program", teamTitle: "A team you can", teamOutline: "talk to.", teamText: "YASAWI STARTUP administrators keep team roles and contact details current.", teamPhoto: "Team member photo",
    partnersEye: "Innovation ecosystem", partnersTitle: "Our", partnersOutline: "partners.", partnersText: "Organizations helping us grow entrepreneurship and take teams to the next level.",
    newsEye: "YASAWI and AYU news", newsTitle: "Latest", newsOutline: "updates.", universityNews: "University news", openPublication: "Open publication",
    ctaEye: "The next cohort starts with you", ctaTitle: "Ready to take", ctaOutline: "the first step?", ctaText: "The application takes about five minutes. We will send you a clear next step after review."
  },
  apply: { eye: "Apply to YASAWI STARTUP", title: "Choose your path.", outline: "Start moving.", description: "Select a program and tell us a little about yourself. The team will help define the next step.", points: ["Free programs", "Clear selection process", "Response after review"], success: "Application received", thanks: "Thank you! The YASAWI STARTUP team will contact you after reviewing your application.", home: "Back to home", select: "Choose a program", name: "What is your name?", namePlaceholder: "Full name", phone: "Phone", idea: "Tell us about yourself or your project", ideaPlaceholder: "What would you like to learn, or what problem does your project solve?", consent: "I consent to the processing of my data for this application and have read the", policy: "privacy policy", error: "We could not submit your application. Please try again.", sending: "Sending…", submit: "Submit application" },
  pages: {
    programs: { eye: "YASAWI STARTUP programs", title: "Choose your", outline: "starting point.", description: "Build digital skills, turn an idea into a product or accelerate a working startup.", details: "Program details", subtitles: ["From idea to first product", "From MVP to growth", "Skills for a digital future"] },
    startups: { eye: "YASAWI portfolio", ideas: "ideas.", paths: "growth paths.", description: "Explore projects by focus area and discover teams worth meeting.", choose: "Choose a project", photo: "A team photo appears when provided; otherwise the signature generative visual remains.", markets: "Open to different markets", marketsTitle: "From social impact", marketsOutline: "to DeepTech.", principles: [["Impact", "The project solves a clear problem for people or organizations."], ["Technology", "The team uses digital, engineering or scientific tools."], ["Validation", "Every idea goes through interviews, prototyping and demand testing."]], story: "The next story could be yours", big: "Big projects begin", first: "with a first version.", launch: "Launch your project" },
    aboutNumbers: { eye: "In numbers", title: "Growth you can", outline: "measure.", text: "Behind the numbers are participants, products, partnerships and new entrepreneurial experience." },
    faq: { title: "Straight answers,", outline: "without the noise.", description: "Everything you need to know before applying and starting a program.", noAnswer: "Still have a question?", write: "Talk to our team.", text: "We will help you understand which program fits and how to prepare." }
  }
};

const tr: typeof ru = {
  nav: { incubation: "Kuluçka", acceleration: "Hızlandırma", education: "BT eğitimi", startups: "Girişimler", gallery: "Galeri", about: "Hakkımızda", apply: "Başvur", programs: "Tüm programlar", faq: "SSS", navigation: "Gezinme", contacts: "İletişim", privacy: "Kişisel verilerin işlenmesi", openMenu: "Menüyü aç", closeMenu: "Menüyü kapat", language: "Site dili" },
  footer: { description: "Hoca Ahmet Yesevi Uluslararası Türk-Kazak Üniversitesi iş kuluçka merkezi.", slogan: "FİKRİNİ HAYATA GEÇİR" },
  common: { more: "Detaylar", free: "Ücretsiz", paid: "Ücretli", open: "Başvurular açık", soon: "Yakında", closed: "Başvurular kapalı", weeks: "hafta", price: "ücret", runs: "yıllık dönem", equity: "hisse", apply: "Başvur", ask: "Soru sor" },
  home: {
    eyebrow: "Resmî AYU programı · Türkistan", title: "Fikrin daha", outline: "ileriye gidebilir.", description: "Öğrenci ve araştırmacıların fikirlerini Üniversite Ticarileştirme Ofisinin desteğiyle ürüne, pilota ve şirkete dönüştürüyoruz.", choose: "Program seç",
    cohort: { open: "Ön kayıtlar açık", soon: "Yeni dönem yakında", closed: "Başvurular sona erdi", note: "Yeni dönem tarihleri kayıt sürecinden sonra açıklanacaktır" },
    operator: "Program yürütücüsü", operatorName: "Hoca Ahmet Yesevi Uluslararası Türk-Kazak Üniversitesi Ticarileştirme Ofisi", verify: "AYU sitesinde doğrula",
    entry: "Üç başlangıç yolu", chooseTitle: "Aşamanıza uygun", chooseOutline: "programı seçin.", chooseText: "Bugün elinizde olanla başlayın; doğru sonraki adımı birlikte bulalım.",
    programTexts: ["Çözmek istediğiniz bir fikir, araştırma veya sorun var.", "MVP'niz ve kullanıcılarınız var; büyümeyi hızlandırmak istiyorsunuz.", "Dijital beceriler edinip ilk projenizi yapmak istiyorsunuz."],
    proofEye: "Vaat değil, sonuç", proofTitle: "Bağlamı olan", proofOutline: "rakamlar.", proofText: "Program göstergeleri YASAWI STARTUP ekibi tarafından güncel tutulur.", source: "Resmî kaynak",
    statLabels: ["kayıtlı katılımcı", "tamamlanan dönem", "kuluçka haftası", "vitrindeki girişim"], statNotes: ["Program verilerine göre", "Program ekibi günceller", "Ölçülebilir üç aşama", "Yayımlanmış projelerden hesaplanır"],
    selectionEye: "Şeffaf seçim", selectionTitle: "Başvurudan sonra", selectionOutline: "ne olur?", selection: [["Başvuru", "Programı seçip kendinizi veya projenizi kısaca anlatırsınız."], ["İnceleme", "Ekip temel ölçütlere uygunluğu değerlendirir."], ["Tanışma", "Kısa görüşme doğru program yolunu belirlemeye yardımcı olur."], ["Karar", "Program başlamadan önce yanıt ve açık yönergeler alırsınız."]],
    help: "Başvurmadan önce yardıma mı ihtiyacınız var?", helpText: "Ekibe yazın:", teamEye: "Programın arkasındaki insanlar", teamTitle: "Ulaşabileceğiniz", teamOutline: "bir ekip.", teamText: "Ekip rolleri ve iletişim bilgileri YASAWI STARTUP yöneticileri tarafından güncel tutulur.", teamPhoto: "Ekip üyesi fotoğrafı",
    partnersEye: "İnovasyon ekosistemi", partnersTitle: "Bizim", partnersOutline: "ortaklarımız.", partnersText: "Girişimciliği birlikte geliştirdiğimiz ve ekiplerin büyümesine destek olan kuruluşlar.",
    newsEye: "YASAWI ve AYU haberleri", newsTitle: "Son", newsOutline: "gelişmeler.", universityNews: "Üniversite haberleri", openPublication: "Yayını aç",
    ctaEye: "Yeni dönem seninle başlar", ctaTitle: "İlk adımı atmaya", ctaOutline: "hazır mısın?", ctaText: "Başvuru yaklaşık beş dakika sürer. İncelemeden sonra sonraki adımı açıkça ileteceğiz."
  },
  apply: { eye: "YASAWI STARTUP başvurusu", title: "Yolunu seç.", outline: "Harekete geç.", description: "Bir program seçin ve kendinizden kısaca bahsedin. Ekip sonraki adımı belirlemenize yardımcı olacaktır.", points: ["Ücretsiz programlar", "Açık seçim süreci", "İnceleme sonrası yanıt"], success: "Başvuru alındı", thanks: "Teşekkürler! YASAWI STARTUP ekibi incelemenin ardından sizinle iletişime geçecektir.", home: "Ana sayfaya dön", select: "Program seçin", name: "Adınız nedir?", namePlaceholder: "Ad soyad", phone: "Telefon", idea: "Kendinizi veya projenizi anlatın", ideaPlaceholder: "Ne öğrenmek istiyorsunuz veya projeniz hangi sorunu çözüyor?", consent: "Başvurumun değerlendirilmesi için verilerimin işlenmesini kabul ediyor ve", policy: "gizlilik politikasını onaylıyorum", error: "Başvuru gönderilemedi. Lütfen tekrar deneyin.", sending: "Gönderiliyor…", submit: "Başvuruyu gönder" },
  pages: {
    programs: { eye: "YASAWI STARTUP programları", title: "Başlangıç", outline: "noktanızı seçin.", description: "Dijital beceri kazanın, fikrinizi ürüne dönüştürün veya çalışan girişiminizi hızlandırın.", details: "Program detayları", subtitles: ["Fikirden ilk ürüne", "MVP'den büyümeye", "Dijital gelecek için beceriler"] },
    startups: { eye: "YASAWI portföyü", ideas: "fikir.", paths: "büyüme yolu.", description: "Projeleri alanlarına göre keşfedin ve tanışmak istediğiniz ekipleri bulun.", choose: "Proje seçin", photo: "Ekip fotoğraf eklediğinde kartta gösterilir; yoksa özgün görsel kompozisyon korunur.", markets: "Farklı pazarlara açığız", marketsTitle: "Sosyal etkiden", marketsOutline: "DeepTech'e.", principles: [["Fayda", "Proje insanların veya kurumların net bir sorununu çözer."], ["Teknoloji", "Ekip dijital, mühendislik ya da bilimsel araçlar kullanır."], ["Doğrulama", "Her fikir görüşme, prototip ve talep testinden geçer."]], story: "Sıradaki hikâye sizin olabilir", big: "Büyük projeler", first: "ilk sürümle başlar.", launch: "Projeni başlat" },
    aboutNumbers: { eye: "Rakamlarla", title: "Ölçülebilir", outline: "büyüme.", text: "Bu rakamların arkasında katılımcılar, ürünler, ortaklıklar ve girişimcilik deneyimi var." },
    faq: { title: "Açık ve", outline: "doğrudan yanıtlar.", description: "Başvuru ve program başlangıcından önce bilmeniz gerekenler.", noAnswer: "Yanıtı bulamadınız mı?", write: "Ekibimize yazın.", text: "Size uygun programı seçmenize ve hazırlanmanıza yardımcı oluruz." }
  }
};

export const messages: Record<Locale, typeof ru> = { ru, kk, en, tr };
export type Messages = typeof ru;
