import type { Metadata } from "next";
import "../pages.css";
import { Eyebrow, PageHero, Reveal, SiteLayout } from "@/components/site-shell";
import { getLocale } from "@/i18n/server";
import { managedPageMetadata } from "@/lib/seo";

export async function generateMetadata(): Promise<Metadata> { return managedPageMetadata(await getLocale(), "privacy"); }

export default async function PrivacyPage() {
  const locale = await getLocale();
  const copy = {
    ru: { hero: ["Прозрачность", "Как мы используем", "данные заявки.", "Коротко и понятным языком о том, какие сведения получает команда программы и зачем они нужны."], updated: "Последнее обновление: 19 августа 2026", important: "Важно", notice: "Это рабочая редакция для сайта. Перед публичным запуском её необходимо согласовать с ответственным подразделением университета.", sections: [["1. Какие данные мы получаем", "Вы указываете выбранную программу, имя, email, номер телефона и описание идеи, проекта или образовательной цели."], ["2. Для чего они нужны", "Данные используются только для рассмотрения заявки, связи с кандидатом, определения подходящей программы и организации участия."], ["3. Кто работает с данными", "Доступ получают уполномоченные сотрудники Офиса коммерциализации и команды YASAWI STARTUP."], ["4. Передача третьим лицам", "Мы не используем данные для рекламы и не передаём их без законного основания или отдельного согласия."], ["5. Как задать вопрос", "По вопросам обработки или удаления заявки напишите нам по адресу"]] },
    kk: { hero: ["Ашықтық", "Өтінім деректерін", "қалай пайдаланамыз.", "Бағдарлама командасы қандай мәлімет алады және оның не үшін қажет екенін түсінікті тілмен баяндаймыз."], updated: "Соңғы жаңарту: 19 тамыз 2026", important: "Маңызды", notice: "Бұл — сайтқа арналған жұмыс нұсқасы. Жариялар алдында университеттің жауапты бөлімімен келісу қажет.", sections: [["1. Қандай деректер аламыз", "Сіз таңдаған бағдарламаны, аты-жөніңізді, email, телефон нөмірін және идея, жоба немесе оқу мақсатының сипаттамасын бересіз."], ["2. Деректер не үшін қажет", "Деректер өтінімді қарау, үміткермен байланысу, қолайлы бағдарламаны анықтау және қатысуды ұйымдастыру үшін пайдаланылады."], ["3. Деректермен кім жұмыс істейді", "Деректерге Коммерцияландыру офисі мен YASAWI STARTUP командасының уәкілетті қызметкерлері қол жеткізеді."], ["4. Үшінші тұлғаларға беру", "Деректерді жарнамаға пайдаланбаймыз және заңды негізсіз немесе бөлек келісімсіз бермейміз."], ["5. Сұрақ қою", "Өтінім деректерін өңдеу немесе жою мәселесі бойынша мына мекенжайға жазыңыз:"]] },
    en: { hero: ["Transparency", "How we use", "application data.", "A clear explanation of what information the program team receives and why it is needed."], updated: "Last updated: 19 August 2026", important: "Important", notice: "This is a working website version and must be approved by the responsible University unit before public launch.", sections: [["1. Data we collect", "You provide the selected program, your name, email, phone number and a description of your idea, project or learning goal."], ["2. Why we need it", "Data is used only to review the application, contact you, identify a suitable program and organize participation."], ["3. Who can access it", "Authorized Commercialization Office and YASAWI STARTUP team members involved in selection and program support can access it."], ["4. Sharing with third parties", "We do not use application data for advertising or share it without a legal basis or separate consent."], ["5. Questions and deletion", "For questions about processing or deleting an application, email"]] },
    tr: { hero: ["Şeffaflık", "Başvuru verilerini", "nasıl kullanıyoruz.", "Program ekibinin hangi bilgileri aldığı ve bunlara neden ihtiyaç duyduğu hakkında açık bir açıklama."], updated: "Son güncelleme: 19 Ağustos 2026", important: "Önemli", notice: "Bu, site için çalışma sürümüdür. Kamuya açılmadan önce Üniversitenin sorumlu birimi tarafından onaylanmalıdır.", sections: [["1. Aldığımız veriler", "Seçtiğiniz programı, adınızı, e-posta adresinizi, telefon numaranızı ve fikir, proje veya eğitim hedefi açıklamanızı paylaşırsınız."], ["2. Neden gereklidir", "Veriler yalnızca başvuruyu değerlendirmek, sizinle iletişim kurmak, uygun programı belirlemek ve katılımı düzenlemek için kullanılır."], ["3. Kimler erişebilir", "Seçim ve program desteğinde görevli Ticarileştirme Ofisi ve YASAWI STARTUP yetkilileri erişebilir."], ["4. Üçüncü taraflarla paylaşım", "Verileri reklam için kullanmayız; yasal dayanak veya ayrı onay olmadan paylaşmayız."], ["5. Soru ve silme talebi", "Başvurunun işlenmesi veya silinmesiyle ilgili olarak şu adrese yazın:"]] },
  }[locale];
  return <SiteLayout><PageHero eyebrow={copy.hero[0]} title={copy.hero[1]} outline={copy.hero[2]} description={copy.hero[3]} /><section className="section shell privacy-content"><Reveal><small>{copy.updated}</small><div className="privacy-notice"><strong>{copy.important}</strong><p>{copy.notice}</p></div>{copy.sections.map(([title, text], index) => <div key={title}><h2>{title}</h2><p>{text}{index === copy.sections.length - 1 && <> <a href="mailto:yassawi_commerc@ayu.edu.kz">yassawi_commerc@ayu.edu.kz</a>.</>}</p></div>)}</Reveal></section></SiteLayout>;
}
